#+TITLE:     OpenStack Notes
#+AUTHOR:    Chandra Mohan Babu, Nadiminti
#+EMAIL:     nadiminti.chandra@gmail.com
#+LANGUAGE:  en
#+INFOJS_OPT: view:showall toc:t ltoc:nil mouse:underline path:http://orgmode.org/org-info.js
#+LINK_HOME: 
#+LINK_UP: 
#+LaTeX_CLASS: smarticle
#+LaTeX_HEADER: \pdfmapfile{/home/neilsen/texmf/fonts/map/dvips/libertine/libertine.map}
#+LaTeX_HEADER: \usepackage[ttscale=.875]{libertine}
#+LaTeX_HEADER: \usepackage{sectsty}
#+LaTeX_HEADER: \sectionfont{\normalfont\scshape}
#+LaTeX_HEADER: \subsectionfont{\normalfont\itshape}
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: H:4 num:t toc:t \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t
#+STARTUP: showall

#+LINK: OpenStack http://openstack.org

----------------------------------------------------------------------------------------------------
* Introduction
    *OpenStack*
    - is an *open source software for creating private and public clouds*
    - is an open source platform that lets you build an Infrastructure as a Service (IaaS) cloud that runs on commodity hardware
    - is *designed for horizontal scalability*, so you can easily add new compute, network, and storage resources to grow your cloud over time.
** Openstack Links
       [[OpenStack][OpenStack Home]]
       [[http://docs.openstack.org/ops/][OpenStack Operations guide]]
       [[http://docs.openstack.org/][OpenStack Docs]]
           - OpenStack Installation Guides
           - OpenStack Training Guides  http://docs.openstack.org/training-guides/content/
           - OpenStack Configuration Reference http://docs.openstack.org/havana/config-reference/content/
           - OpenStack API Quick Start    http://docs.openstack.org/api/quick-start/content/
           - ...
** Projects
*** Compute(nova)
        Compute API service(openstack-nova-api)
*** Networking(neutron)
**** Common components
     The Networking common component configuration includes the authentication mechanism, message broker, and plug-in.
***** Modular Layer 2 (ML2) plug-in
      The ML2 plug-in uses the Open vSwitch (OVS) mechanism (agent) to build virtual networking framework for instances.
      openvswitch
      neutron-openvswitch-agent
        - The OVS service provides the underlying virtual networking framework for instances.
        - The integration bridge br-int handles internal instance network traffic within OVS.
        - The external bridge br-ex handles external instance network traffic within OVS.
          + it requires a port on the physical external network interface to provide instances with external network access.
***** neutron-l3-agent
      The Layer-3 (L3) agent provides *routing services* for instance virtual networks.
***** neutron-dhcp-agent
      The DHCP agent provides *DHCP services* for instance virtual networks.
***** neutron-metadata-agent
      The metadata agent provides *configuration information such as credentials* for remote access to instances.
*** Storage

* Architectures
  Openstack high level architecture- http://docs.openstack.org/ops-guide/architecture.html

  Example Architecture - Legacy Networking (nova) http://docs.openstack.org/ops-guide/arch_example_nova_network.html

  Example Architecture - OpenStack Networking(neutron) http://docs.openstack.org/ops-guide/arch_example_neutron.html

* Deployment/Installation
   [[http://docs.openstack.org/developer/devstack/][DevStack]] - an OpenStack Community Production
   http://www.sebastien-han.fr/blog/2013/08/08/devstack-in-1-minute/

* Development
** Python
    [[http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html][Code Like a Pythonista: Idiomatic Python]]
** Eclipse(Juno)
    PyDev http://pydev.org/updates
    plantUML http://plantuml.sourceforge.net/updatesitejuno/
    black-skin
        https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite
        http://eclipse.jeeeyul.net/update/
        JSF - Web pages editor?
        my settings file
    https://wiki.openstack.org/wiki/NeutronDevelopment
** My Sequence Diagrams
*** VPNAAS SEQ-DIAGRAM CISCO CSR

#+begin_src plantuml :file vpnaas_seq_diagram_cisco_csr.png
#+INCLUDE: "~/vpnaas_seq_diagram_cisco_csr.txt"
#+end_src

*** L3AAS SEQ-DIAGRAM CISCO_CSR

#+begin_src plantuml :file l3aas_seq_diagram_cisco_csr.png
#+INCLUDE: "~/l3aas_seq_diagram_cisco_csr.txt"
#+end_src

* Unit Test

* Tempest
   # http://wikicentral.cisco.com/display/PROJECT/Tempest+-+Integrated+Testing
   https://git.openstack.org/cgit/openstack/tempest/tree/

* CI

* Upstreaming
    Login - https://www.openstack.org/Security/login/

* Others
    - Northbound API
    - Southbound API
    - eNovance, HP, Rackspace
    - Canonical, Red Hat, and SUSE, Rackspace, Piston, SwiftStack, or Cloudscaling.
    - http://en.wikipedia.org/wiki/Eucalyptus_%28software%29
    - http://docs.openstack.org/image-guide/content/ch_converting.html

